spring:
  datasource:
    url: jdbc:postgresql://ecommerce_db:5432/postgres
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always




#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ecommerce
#    username: postgres
#    password: 1234
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true